# Generated by Django 5.0.1 on 2024-01-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=30)),
                ('mothername', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=50)),
                ('grno', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('doa', models.DateField()),
                ('dob', models.DateField()),
                ('adharno', models.PositiveIntegerField()),
                ('mobileno', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('classes', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('mark', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('classes', models.CharField(max_length=30)),
                ('division', models.CharField(max_length=30)),
                ('rollno', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField()),
            ],
        ),
    ]
